// Build theme.css from src/theme.css: every url(fonts/<file>) becomes a base64 data URI, because Obsidian's theme
// guidelines want fonts embedded (no remote loading) and a theme installs as theme.css + manifest.json only.
// No dependencies. Usage: node scripts/build.mjs [--check]   (--check: fail if theme.css is not what the source builds)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(ROOT, 'src', 'theme.css'), 'utf8');
const { version } = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
const body = src.replace(/url\((['"]?)fonts\/([\w.-]+)\1\)/g, (m, q, f) => {
  const p = join(ROOT, 'fonts', f);
  if (!existsSync(p)) throw new Error(`missing font: fonts/${f}`);
  return `url("data:font/woff2;base64,${readFileSync(p).toString('base64')}")`;
});
const out = `/* Torchlight ${version}: generated by scripts/build.mjs from src/theme.css; edit the source, not this file. */\n${body}`;
const target = join(ROOT, 'theme.css');
if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== out) { console.error('theme.css is stale: run npm run build'); process.exit(1); }
  console.log('theme.css up to date');
} else {
  writeFileSync(target, out);
  console.log(`theme.css ${(out.length / 1024).toFixed(0)} KB`);
}
